### ISSUE TITLE
Story fails to download, no error message displayed

### ISSUE THREAD

**Issue by cyian-1756** [sexypants/chyoa-scraper#1]
When I run the command `python3 -m chyoa download 'https://chyoa.com/story/Aaralon%27s-Discoveries.276' aaralons_discoveries` I get `Finished in 0.000 seconds.` as the output but no story is downloaded

I have test it with 3 different stories. Running on Ubuntu 16.04 with Python 3.5.2

**Comment by sexypants** [comment]
Part of the download routine was indented one level too deep, so it would only download the story if the URL looked incorrect. Sorry about that.

Fixed in 468a2dc.

Relevant portion [here](https://github.com/sexypants/chyoa-scraper/commit/468a2dc35143142a5843458553da3f2388d4b061#diff-9ffafd2cb15af4687d97967f20e50500L19).
